@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Dec 08 14:30:39 -0500 2021
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Test_ARM_SC_behav -key {Behavioral:sim_1:Functional:Test_ARM_SC} -tclbatch Test_ARM_SC.tcl -view C:/School/Fall_2021/eece351/ARM_MultiCycle/ARM_MultiCycle.srcs/sim_1/imports/ARM_MultiCycle/Test_ARM_SC_behav.wcfg -log simulate.log"
call xsim  Test_ARM_SC_behav -key {Behavioral:sim_1:Functional:Test_ARM_SC} -tclbatch Test_ARM_SC.tcl -view C:/School/Fall_2021/eece351/ARM_MultiCycle/ARM_MultiCycle.srcs/sim_1/imports/ARM_MultiCycle/Test_ARM_SC_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
